_prefs: 
  mapid: goteborgcom.b8abf2a3
  saveCenter: false
_properties: 
  bridge: 
    "group-by": layer
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - 11.9661
  - 57.7036
  - 16
description: ''
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 18
minzoom: 8
name: goteborg.com - sandbox
source: "mapbox:///mapbox.mapbox-streets-v5"
styles: 
  - style.mss
  - road.mss
  - labels.mss
  - variables.mss
  - Övrigt.mss
template: ''
